#!/bin/sh

if ! type "brew" >/dev/null; then
  echo "Installing Homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  echo "Homebrew already installed"
fi

echo "Updating Homebrew formulae..."
brew update 2>/dev/null

echo "Installing prerequisites..."
if [ -z $(brew list -1 | grep -i "git") ]; then
  brew install git
fi
if [ -z $(brew tap | grep -i "Homebrew/bundle") ]; then
  brew tap "Homebrew/bundle"
fi

if [ ! -d "$HOME/.dotfiles" ]; then
  echo "Cloning dotfiles..."
  git clone "https://github.com/linkyndy/.dotfiles.git" "$HOME/.dotfiles"
else
  echo "Dotfiles already cloned"
fi

echo "Symlinking dotfiles..."
ln -sf "$HOME/.dotfiles/.zshrc" "$HOME"
ln -sf "$HOME/.dotfiles/.Brewfile" "$HOME"

echo "Installing Homebrew Bundle formulae..."
brew bundle --global

if ! rbenv versions | grep -q "2.2.3"; then
  echo "Installing Ruby 2.2.3..."
  rbenv install -s "2.2.3"
else
  echo "Ruby 2.2.3 already installed"
fi

echo "Updating RubyGems..."
gem update --system

if ! gem list | grep -q "bundler"; then
  echo "Installing Bundler..."
  gem install bundler
else
  echo "Updating Bundler..."
  gem update bundler
fi

case "$SHELL" in
  */zsh) : ;;
  *)
    echo "Changing the shell to zsh..."
    chsh -s "$(which zsh)"
    ;;
esac

cowsay 'Mac is set up!'
