#!/bin/sh

if ! type "brew" >/dev/null; then
  echo "Installing Homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  echo "Homebrew already installed"
fi

echo "Updating Homebrew formulae..."
brew update

echo "Installing prerequisites..."
if ! brew list -1 | grep -q "git"; then
  brew install git
fi
if ! brew tap | grep -q "homebrew/bundle"; then
  brew tap "Homebrew/bundle"
fi

if [ ! -d "$HOME/.dotfiles" ]; then
  echo "Cloning dotfiles..."
  git clone "https://github.com/linkyndy/.dotfiles.git" "$HOME/.dotfiles"
else
  echo "Dotfiles already cloned"
fi

echo "Symlinking dotfiles..."
ln -sf "$HOME/.dotfiles/.zshrc" "$HOME"
ln -sf "$HOME/.dotfiles/.gemrc" "$HOME"
ln -sf "$HOME/.dotfiles/.gitconfig" "$HOME"
ln -sf "$HOME/.dotfiles/.Brewfile" "$HOME"
ln -sfF "$HOME/.dotfiles/.atom" "$HOME"

echo "Installing Homebrew Bundle formulae..."
brew bundle --global

if [ ! $(apm list --installed --bare | sed '/^$/d' | wc -l) -eq $(cat "$HOME/.dotfiles/.atom/packages.txt" | wc -l) ]; then
  echo "Installing Atom packages..."
  apm install --packages-file "$HOME/.dotfiles/.atom/packages.txt"
else
  echo "Atom packages already installed"
fi

if ! rbenv versions | grep -q "2.2.3"; then
  echo "Installing Ruby 2.2.3..."
  rbenv install -s "2.2.3"
else
  echo "Ruby 2.2.3 already installed"
fi

echo "Setting default Ruby..."
rbenv global "2.2.3"

echo "Updating RubyGems..."
gem update --system

if ! gem list | grep -q "bundler"; then
  echo "Installing Bundler..."
  gem install bundler
else
  echo "Updating Bundler..."
  gem update bundler
fi

if ! pyenv versions | grep -q "2.7.13"; then
  echo "Installing Python 2.7.13..."
  pyenv install -s "2.7.13"
else
  echo "Python 2.7.13 already installed"
fi

echo "Setting default Python..."
pyenv global "2.7.13"

case "$SHELL" in
  */zsh) : ;;
  *)
    echo "Changing the shell to zsh..."
    chsh -s "$(which zsh)"
    ;;
esac

cowsay 'Mac is set up!'
